name: Deploy to AWS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 3.253.118.35
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
           # 1. Prepare environment
          
            cd /home/ec2-user
            sudo yum install git docker -y
            sudo systemctl start docker
            sudo usermod -aG docker ec2-user || true
            
            # 2. Deploy into a dedicated folder
            APP_DIR="/home/ec2-user/dbs-project"
            if [ ! -d "$APP_DIR" ]; then
              git clone https://github.com/morningstar7137/dbs-devops-assignment.git $APP_DIR
            else
              cd $APP_DIR && git pull origin main
            fi
            
            # 3. Build and Run from the new folder
            cd $APP_DIR
            sudo docker stop my-app || true
            sudo docker rm my-app || true
            sudo docker build -t my-app .
            sudo docker run -d --name my-app -p 80:80 my-app
